Redux react components
Alfredbis29/Book-Store-CMS pull request #5
Opened 2022-05-11 12:54 UTC by Alfredbis29

2022-05-11 19:20 UTC, Kingstalux requested changes
Hi @Alfredbis29, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966](https://user-images.githubusercontent.com/85113567/167928557-d5648cc6-30b6-4e5b-aa41-dcb047b7aef5.gif)

## Highlights  👏 
✅ Books can be added and removed 🔥 
✅ Good pull request description 👍 
✅ Linters are passing 👏 


## Required Changes ♻️
- [ ] Kindly arrange your categories reducer so that when a user clicks on the `check status` button, the text `under construction` should be displayed 👍 Right now the button does not have any functionality. Kindly fix that 😄 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 06:05 UTC, Alfredbis29 commented
Hello @Kingstalux, I didn't see that requirement on this milestone of this project please check again all requirements, I'm looking forward to having your feedback. Please

2022-05-12 06:09 UTC, Kingstalux commented
> Hello @Kingstalux, I didn't see that requirement on this milestone of this project please check again all requirements, I'm looking forward to having your feedback. Please
![Annotation 2022-05-12 070849](https://user-images.githubusercontent.com/85113567/168003332-4620af57-a4a2-40b2-ad74-2135692c0aab.jpg)
That is it in the project requirements

2022-05-12 06:23 UTC, Alfredbis29 commented
Okay okay 
Thank you

2022-05-12 08:24 UTC, AnselemOdims approved these changes
### Hi  @Alfredbis29 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 08:24 UTC, AnselemOdims commented on src/components/Category.js
> +  const categories = useSelector((state) => state.categories);
- [ ][OPTIONAL] It is usually good practice to put your hooks before any handler functions

2022-05-12 08:33 UTC, merged